#!/usr/bin/python
from kafka import KafkaProducer

producer = KafkaProducer(bootstrap_servers=['172.17.0.1:9092'])
future = producer.send('quickstart-events2' , key= b'my_key', value= b'my_value', partition= 0)

# from kafka import KafkaProducer
#
# producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
# future = producer.send('my_topic' , key= b'my_key', value= b'my_value', partition= 0)
result = future.get(timeout= 10)
# print(result)